apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: balestrino/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: balestrino/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
# portForward:
#   - resourceType: service
#     resourceName: auth-srv
#     port: 3000
#     address: 192.168.1.3
#     localPort: 80
#   - resourceType: service
#     resourceName: client-srv
#     port: 3000
#     address: 192.168.1.3
#     localPort: 80
