apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-claim
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  mountOptions:
    #- hard
    - nfsvers=4.1
  nfs:
    server: "192.168.1.3"
    path: "/data"
