apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:3-jessie
          command:
            - mongod
            - --replSet
            - rs0
            - --bind_ip_all
          ports:
            - containerPort: 27017
              name: web
          volumeMounts:
            - name: database
              mountPath: /data/db
        - name: init-mongo
          image: mongo:3-jessie
          command:
            - bash
            - /config/init.sh
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: "mongo-init"
  volumeClaimTemplates:
    - metadata:
        name: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs.raid5
        resources:
          requests:
            storage: 30Gi
